image: ruby:2.5.1

cache:
  paths:
    - vendor/

test:
  except:
    - tags
  script:
    - bundle
    - bundle exec rake

release:
  only:
    - release@monban/rubygens-core
  script:
    - "git remote add super https://gett-systems:$GITLAB_ACCESS_TOKEN@gitlab.com/cathands-sendai/staff/auth.git"
    - "git remote add github https://getto-systems:$GITHUB_ACCESS_TOKEN@github.com/getto-systems/rubygems-monban-core.git"
    - "git tag $(cat .release-version)"
    - "git push super HEAD:master --tags"
    - "git push github HEAD:master --tags"
