sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.2
notifications:
  slack:
    secure: "gsrS7cLQIsuvrXuc+nQ2zHpn3k5bQ/DgISYYAtaN32CCTFfITw2OIJJ7r/GQCjHfwjrEDB4JTjkAno2aTgNHF/UKgSHPd3oJT4F1XssdQnjmgr8Z1FE5Umt5WNpfUtGPRMIghsXvkdWAXIRtKaOuZiyguyBgvTN7bmA9k+b2rLms/Kc83TvJuF8rldLoly08aZKLiqGy0zC7ODawMf0G83iyvwd7rVmMtMEF1STUf7ydOsiOKamQSWgIaGKFbPh0+5rbq2nnVl31iKOS9ijGPwFAvefUIXTNdDV1NtMxqCcrcUvxXrow9U4De1gxk6euc2Nv46Fo8XNjblz96jh9l/jQhLh+TCnXcBSHFqyM6R5mTmuaZt5ErQzDhlriN4hq9/Q/wsYdEMtmOgw4ejnRvr5+M+h5UpNer9CSx+hzLpxQsZ/YwevF/4OvooVF7uP0atvAksaXYcArRCcB5ubmlIH1Y3XotSuyPKI1n+xrwyTejGrgA/z9+FxYUSIsRpW0oxREYURw+oodNX9VYtbkwemSybJDgAuoprswoRbIiyfVQr/ViWhhUFKmPoGJdKdfBdAnbb8U4a38pBuTNEwzpiREBjqJZSEWmFp9/gV48K2Z3qUxpTJX4A7UVIHMm/2E8DQjutmZyLuw05gpqFc/O3ikeKPPDpQaBDCzD1hiq/s="
deploy:
  provider: rubygems
  gem: monban-core
  on:
    tags: true
  api_key:
    secure: "DdkHZ3zEXiaetZt7r36tbT0+ECCE6meR//2sJo0AgVE5rpWS1tCd0/D/bjrYKyZha7NlGyyXp0/2A5RPdfJVIZiapVHpB2XozZNKcNVvXoeQRchAlHHIbpapiseo+28gCQK5h/K30m7OExCTtoXSGSIUCLeOkIz0AFC/7Aor1e/+38DLK2NvFleYJfAtWedNSe75exygTpca48zwgkwnNyRwenLoA8poDXJKjkElS9Y/Wf/L4HBiCBu2C/9pGZz0Tdf2lMxD9lNsGYbCxCtA3381f6zFt7cNhGY6a6GWvoZInep6C11PrYUT97TmLpgeTqB7hgYtsXxVP6kEEVlPmrNg22nR91YFSohFpvWAlZ7kCUOiQntwo4n0vLtPVvW0nXx0sAk0I2/mIH41Lnj7ekz5BQW0/4K1SQjjqlTQ0J9FVMGd7Y3ewjRmjcJ99kf0vPTqs5zERe9pfnaYzhYkyQggp4ZeGfeOYzYGdx0wtLQDFzMp8KlbpNTSIcpIFhVzvW40or4CdMMDZqn8iFBvfvvRsEpClUnRaybIJJJltIDnb3qCDNoIebDSbuVINjQufApCDXmpoWz3Ec2Gy1YWraaqzWEqfWhKUbTxuEkOxyXFUDtXrWTwKJ67J+JDx/lH5vQFU61Wt8O2lVswuvqhCxO24qFQiYpT8Onjw+GgCSI="
