sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.2
notifications:
  slack:
    secure: "TAH3pmrb9EXNIipvfOPLKJQZHVU7u46YS3URIxZiPaPxka4ZVSqrJuPD91AwJfZLk+aw5wGvSBDwiz8iVpebtQxiz7JLhxAI41R1PsbrhswyPp0N18HF0T998PWgCtbS3Zi8lq8bGijaleTpainlRFBj7mfjSs5ZReM2HCI3qcb66N4B55EiN3qjG9m/OzS0zqbgMZ4l1tgLHoMMbHCCtqfWYTDoErKnIjzjJQcQjcu6r7k6/L2/UKcSN7Bk9dLqakjWC5bo5RQu1PlDwbMJw79XvmuyKpjpiDzBNGUyxDQoa307UmE05PNYsa8zew/dxSf2LLuFZzFTpN5KLg9PllRiDJLKgufsJavJ6/AOThnMo4npCBqkYNmGsY8NcXYlOYu4F/2AKHf799pQ+M0di/tt/ORZkM86D+/1zHLiYOHNnBPZKtjgKAxrBGBhwnvatTRccOQ1OVsgbYKLZ8PBVOZJzPZfsn0y2lcJNEH1s9GqAUPncHxyghZb01oepfD8h51EvEJ3Q3hE6mxQv/2faRVw6r22IzyxJSo4rACuZW2jLmN3nxfqq7MSCuaq9we/NzbHKdu+XKIARjlJeLVjryLvGh3y83iIrTkWLO5l8tURdqxu9T16jWKRkBji1AQTPyj4KwcRruFGrtDg3DD33sdeC/g5qijLoVJxpnxR27o="
deploy:
  provider: rubygems
  gem: monban-core
  on:
    tags: true
  api_key:
    secure: "DdkHZ3zEXiaetZt7r36tbT0+ECCE6meR//2sJo0AgVE5rpWS1tCd0/D/bjrYKyZha7NlGyyXp0/2A5RPdfJVIZiapVHpB2XozZNKcNVvXoeQRchAlHHIbpapiseo+28gCQK5h/K30m7OExCTtoXSGSIUCLeOkIz0AFC/7Aor1e/+38DLK2NvFleYJfAtWedNSe75exygTpca48zwgkwnNyRwenLoA8poDXJKjkElS9Y/Wf/L4HBiCBu2C/9pGZz0Tdf2lMxD9lNsGYbCxCtA3381f6zFt7cNhGY6a6GWvoZInep6C11PrYUT97TmLpgeTqB7hgYtsXxVP6kEEVlPmrNg22nR91YFSohFpvWAlZ7kCUOiQntwo4n0vLtPVvW0nXx0sAk0I2/mIH41Lnj7ekz5BQW0/4K1SQjjqlTQ0J9FVMGd7Y3ewjRmjcJ99kf0vPTqs5zERe9pfnaYzhYkyQggp4ZeGfeOYzYGdx0wtLQDFzMp8KlbpNTSIcpIFhVzvW40or4CdMMDZqn8iFBvfvvRsEpClUnRaybIJJJltIDnb3qCDNoIebDSbuVINjQufApCDXmpoWz3Ec2Gy1YWraaqzWEqfWhKUbTxuEkOxyXFUDtXrWTwKJ67J+JDx/lH5vQFU61Wt8O2lVswuvqhCxO24qFQiYpT8Onjw+GgCSI="
